version: '3.4'

services:
  tftp-hpa:
    restart: always
    image: lnls/tftp-hpa
    ports:
      - "69:69/udp"
    logging:
      options:
        max-size: 50m
    container_name: tftp-hpa
    depends_on:
      - debian-base-image
    volumes:
      - type: bind
        source: ./data/pxelinux.cfg
        target: /tftpboot/pxelinux.cfg
        volume:
          read_only: true
      - type: volume
        source: debian-base-image-volume
        target: /tftpboot/init
        volume:
          read_only: true

  debian-base-image:
    image: lnls/debian-base-image:pre-9.9-kernel-4.9.0-11-20200122
    container_name: debian-base-image
    volumes:
      - type: volume
        source: debian-base-image-volume
        target: /tftpboot/init
        volume:
          read_only: true

volumes:
  debian-base-image-volume:
